spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webtoon_crawler?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 500
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
    show-sql: true

site-url:
  kakao: "https://bff-page.kakao.com/graphql"
  naver:
    weekday: "https://comic.naver.com/api/webtoon/titlelist/weekday"
    finished: "https://comic.naver.com/api/webtoon/titlelist/finished"
    new: "https://comic.naver.com/api/webtoon/titlelist/new"
